import { jobs } from '../data/jobData';
import map from '../data/xianMap.json';
import football from '../data/footballSpatial.json';
import { go, Tag } from '../components/Common';
import { CityMap } from '../components/CityMap';
import { initialA,initialB } from './MapProject';
import { rankPlaces } from '../lib/spatial';

const places=rankPlaces(map.pois,initialA,initialB);
function MiniRecruitment(){return <div className="mini-window recruitment-mini"><div className="mini-top"><span>招聘情报中心</span><span>个人投递工作台</span></div><div className="mini-metrics"><b>{jobs.length}<small>收录岗位</small></b><b>{new Set(jobs.map(j=>j.company)).size}<small>覆盖企业</small></b><b className="accent-number">可追溯<small>原始来源</small></b></div><div className="mini-table">{jobs.slice(0,3).map(j=><div key={j.id}><span className="company-dot"><img src={j.logo} alt=""/></span><b>{j.company}<small>{j.role}</small></b><em>查看证据</em></div>)}</div><div className="mini-evidence"><span>已有证据</span><span>部分匹配</span><span>待补齐</span></div></div>}
function MiniFootball(){const network=football.aggregates['779:1:0'].network,byId=new Map(network.nodes.map(n=>[n.id,n]));return <div className="mini-window football-mini"><div className="mini-top"><span>阿根廷 · 上半场传球网络</span><span>2022 世界杯决赛</span></div><svg viewBox="-5 -8 130 96" className="mini-network" role="img" aria-label="由真实事件计算的传球网络"><rect x="0" y="0" width="120" height="80" fill="#243c30" stroke="#607664" strokeWidth=".4"/><path d="M60 0V80M0 18H18V62H0M120 18H102V62H120" fill="none" stroke="#607664" strokeWidth=".4"/><circle cx="60" cy="40" r="9" fill="none" stroke="#607664" strokeWidth=".4"/>{network.edges.filter(e=>e.count>=4).map(e=>{const a=byId.get(e.a),b=byId.get(e.b);return <line key={`${e.a}-${e.b}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#c9f04a" opacity=".5" strokeWidth={Math.min(1.5,e.count*.08)}/>})}{network.nodes.map(n=><circle key={n.id} cx={n.x} cy={n.y} r="2.2" fill="#e3eebf"/>)}</svg><div className="mini-evidence"><span>传球网络</span><span>向前推进</span><span>事件热区</span></div></div>}
function Product({number,title,subtitle,copy,tags,path,children}){return <article className="project-row"><div className="project-copy"><span className="project-number">PROJECT {number}</span><h2>{title}</h2><h3>{subtitle}</h3><p className="product-one-liner">{copy}</p><div className="tag-row">{tags.map(t=><Tag key={t}>{t}</Tag>)}</div><button className="project-link" onClick={()=>go(path)}>打开产品 <span aria-hidden="true">↗</span></button></div><div className="project-preview">{children}</div></article>}
export function Home(){return <main><section className="hero container refined-hero"><div className="eyebrow"><span>时空信息 · 数据产品 · AI应用</span><span className="quiet-tag">路普昊 / 2027 届硕士</span></div><h1>让数据有位置。<br/><em>让选择有依据。</em></h1><div className="hero-bottom"><p>GIS专业背景，把空间数据和实际问题做成可用的工具。<br/><span>独立完成产品设计、AI辅助编码和测试迭代。</span></p><a className="browse-projects" href="#projects">浏览三个产品 ↓</a></div></section><section className="projects container" id="projects"><div className="section-heading"><span>SELECTED PRODUCTS / 03</span><p>选择地点，比较岗位，理解比赛。</p></div>
 <Product number="01" title="城市会合点" subtitle="一个双方都方便的位置。" copy="设置两个人的出发点，比较周边场所的距离。筛选、选点、保存，一张地图完成。" tags={['真实地图数据','双点决策','本地保存']} path="/projects/meetpoint"><div className="map-home-preview"><div className="mini-top"><span>西安 · 南大街片区</span><span>{map.pois.length} 个候选场所</span></div><CityMap a={initialA} b={initialB} places={places} selected={places[0]} mini/><div className="map-preview-bottom"><b>{places[0]?.name}</b><span>A {places[0]?.da.toFixed(2)} km · B {places[0]?.db.toFixed(2)} km</span></div></div></Product>
 <Product number="02" title="招聘情报中心" subtitle="把岗位信息，变成投递选择。" copy="收录岗位、核对要求、查看简历证据，持续记录自己的投递进度。每个岗位保留来源。" tags={['岗位检索','证据匹配','投递管理']} path="/projects/job-intelligence"><MiniRecruitment/></Product>
 <Product number="03" title="足球数据实验室" subtitle="看见比分背后的空间。" copy="从联赛走进单场比赛，再用传球连接、向前推进和事件热区，看清球队如何组织进攻。" tags={['传球网络','空间聚合','真实事件']} path="/projects/football-analytics"><MiniFootball/></Product>
 </section><section className="about-strip"><div className="container"><span>ABOUT</span><p>西南大学 · 地理信息科学本科<br/>陕西师范大学 · 地理学硕士</p><p>多源时空数据处理<br/>Python · GIS · 数据分析</p><p>Agent任务评测<br/>AI辅助开发 · 产品实现</p></div></section></main>}
